// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrwgh7pZ2AYYgBEXXSCmLpQ6-1ydHcIwU',
    appId: '1:608325273900:web:2573826c045c06f4c10489',
    messagingSenderId: '608325273900',
    projectId: 'nti6-a65a3',
    authDomain: 'nti6-a65a3.firebaseapp.com',
    storageBucket: 'nti6-a65a3.firebasestorage.app',
    measurementId: 'G-KDGSHZJ30R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZkr3KzvOuJ56-p29BhhEmd2ZpPSrUp_A',
    appId: '1:621935208264:android:cdd18ea49869157445757d',
    messagingSenderId: '621935208264',
    projectId: 'nti6-2b1fc',
    storageBucket: 'nti6-2b1fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Iq2KkqShlrMdVIZT-74C4WYEkTM-hM8',
    appId: '1:621935208264:ios:ce58166dacc526af45757d',
    messagingSenderId: '621935208264',
    projectId: 'nti6-2b1fc',
    storageBucket: 'nti6-2b1fc.firebasestorage.app',
    iosBundleId: 'com.example.nti5Firebase',
  );

}